kind: pipeline
type: docker
name: cthunline-api-ci

# when to execute pipeline
trigger:
  branch:
  - master
  - dev
  event:
  - push
  - pull_request

steps:
# wait for database
- name: waiton
  image: akhenakh/drone-waiton:1.0
  settings:
    globaltimeout: 60s
    urls:
    - tcp://mariadb:3306
# install dependencies & setup env
- name: install
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm i
  - cp .env.ci .env.test
# linters
- name: lint
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - install
# tests
- name: test
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm run test
  depends_on:
  - install
  - waiton
# sonarqube scan
- name: sonarqube
  image: pitininja/drone-sonar-plugin:latest
  failure: ignore
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  depends_on:
  - test
  when:
    branch:
    - dev
    event:
    - push

services:
# mariadb service
- name: mariadb
  image: mariadb
  environment:
    MARIADB_RANDOM_ROOT_PASSWORD: yes
    MARIADB_USER: cthunline
    MARIADB_PASSWORD: cthunline
    MARIADB_DATABASE: cthunline_ci

---
kind: pipeline
type: docker
name: cthunline-api-cd

# when to execute pipeline
trigger:
  event:
  - tag

# disable default cloning
clone:
  disable: true

# building and publishing docker image
steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/cthunline/cthunline-docker.git .
- name: docker  
  image: plugins/docker
  settings:
    repo: cthunline/cthunline
    tags:
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: docker_user
    password:
      from_secret: docker_token
