kind: pipeline
type: docker
name: cthunline-api-ci

trigger:
  branch:
  - sonar
  event:
  - push

steps:
- name: sonarqube
  image: plugins/sonarqube-scanner:latest
  failure: ignore
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    output-file: /tmp/output.txt
  when:
    branch:
    - sonar
    event:
    - push
