services:
- name: postgres
  image: postgres:bookworm
  pull: true
  environment:
    POSTGRES_USER: cthunline
    POSTGRES_PASSWORD: cthunline
    POSTGRES_DB: cthunline_ci
- name: keydb
  image: eqalpha/keydb:latest
  pull: true

steps:
- name: install
  image: node:20-alpine
  pull: true
  commands:
  - npm i
  - cp .env.ci .env.test
  when:
    branch:
    - master
    event:
    - push
    - pull_request
- name: lint
  image: node:20-alpine
  pull: true
  commands:
  - npm run lint
  depends_on:
  - install
  when:
    branch:
    - master
    event:
    - push
    - pull_request
- name: test
  image: node:20-alpine
  pull: true
  commands:
  - npm run test
  depends_on:
  - install
  when:
    branch:
    - master
    event:
    - push
    - pull_request
- name: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  pull: true
  failure: ignore
  depends_on:
  - install
  environment:
    SONAR_HOST_URL:
      from_secret: sonar_host
    SONAR_TOKEN:
      from_secret: sonar_token
  when:
    branch:
    - master
    event:
    - push
